Allow the XMPP bridge to use slack compatible webhooks
42wim/matterbridge pull request #1364
Opened 2021-01-19 17:36 UTC by Polynomdivision

This PR tries to work on #1082 by giving the user the possibility to set a webhook for the XMPP bridge to allow user name spoofing.
This requires a prosody server with `mod_slack_webhooks` installed.

To add a webhook, just add the `WebhookURL` option to your XMPP section

```
[...]
[xmpp]
        [xmpp.test]
        [...]
        RemoteNickFormat="{NICK}"
        WebhookURL="https://some.server/msg/abc123"
[...]
```

This would POST a message to `https://some.server/msg/abc123/<channel>` when a message is received in the channel `<channel>`. Setting a webhook disables sending messages via the connected XMPP account on all channels that this account mirrors.

As mentioned in #1082 , using `mod_rest` may be the better solution, but it would currently require running prosody trunk or the yet unreleased version 0.12, so I settled on `mod_slack_webhook`.

2021-01-20 23:03 UTC, 42wim requested changes
Thanks 👍 some small issues
Are you also willing to add extra documentation in the `xmpp` section of `matterbridge.toml.sample` ?

2021-01-21 12:03 UTC, Polynomdivision commented on bridge/xmpp/xmpp.go
> +		return msg.ID, nil
At least not currently. When prosody 0.12 gets released and I will, probably, rewrite this to use mod_rest instead, then it might be possible.

2021-01-21 12:03 UTC, Polynomdivision commented on bridge/xmpp/xmpp.go
> +		webhookURL:         cfg.GetString("WebhookUrl"),
Done

2021-01-21 21:50 UTC, merged

2021-01-21 21:50 UTC, 42wim commented
Thanks!