[fix] telegram: Add's comments to message
42wim/matterbridge pull request #1652
Opened 2021-12-07 17:43 UTC by soloam

This is a change to handle comments in telegram messages!

Some messages in telegram have comments added to the message! This normally is the description in images or links. This changes appends the comment to the message if available.

This should fix the issue in #1649

2021-12-07 20:23 UTC, 42wim commented
hi @soloam did you test this? the code doesn't build

2021-12-08 23:23 UTC, soloam commented
I'm sorry for the confusion, I pushed the wrong branch! I corrected the branch and updated the new change! Discord was ignoring the image caption if a text was in the image! The caption contains important information from the extra! It should be forwarded!

2021-12-11 23:06 UTC, 42wim commented
But this change will remove any text ?

2021-12-11 23:09 UTC, 42wim commented on bridge/discord/webhook.go
> +			content := fi.Comment
```suggestion
			content := fi.Comment
			if msg.Text != "" {
				content = msg.Text
			}
```

2021-12-11 23:10 UTC, 42wim requested changes

2021-12-11 23:10 UTC, 42wim commented on bridge/discord/webhook.go
> +			content := fi.Comment
can you test with this change, so we only add the comment when there is empty text

2021-12-12 00:13 UTC, soloam commented
That was the original behavior! The problem is that when it's forwarded (for example telegram writers "forwarded from") or anything is written on the text, the comments are removed.

2021-12-12 00:24 UTC, 42wim commented
Ok, as I'm not using telegram I take you for your word :)

2021-12-12 00:30 UTC, 42wim approved these changes

2021-12-12 00:40 UTC, merged